services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pulse-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-service:
    build:
      context: .
      dockerfile: Pulse.ApiService/Dockerfile
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8081
      - PulseSqlDb__ConnectionString=Server=host.docker.internal\DEV;Database=dbPulse;User Id=sa;Password=$$T3ph3n$$$$$;TrustServerCertificate=true;ConnectRetryCount=5;ConnectRetryInterval=5;
      - ConnectionStrings__cache=redis:6379
    depends_on:
      - redis
    networks:
      - pulse-network

  web:
    build:
      context: .
      dockerfile: Pulse.Web/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ApiServiceUrl=http://api-service:8081
      - ConnectionStrings__cache=redis:6379
    depends_on:
      - api-service
    networks:
      - pulse-network

networks:
  pulse-network:
    driver: bridge