<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>a92dd10d-cacb-4034-8c7d-5b7f23d1ab74</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PulseAI\Ali\**" />
    <Compile Remove="PulseAI\Flapper\**" />
    <Content Remove="PulseAI\Ali\**" />
    <Content Remove="PulseAI\Flapper\**" />
    <EmbeddedResource Remove="PulseAI\Ali\**" />
    <EmbeddedResource Remove="PulseAI\Flapper\**" />
    <None Remove="PulseAI\Ali\**" />
    <None Remove="PulseAI\Flapper\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pulse.Models\Pulse.Models.csproj" />
    <ProjectReference Include="..\Pulse.ServiceDefaults\Pulse.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.1" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.2.0" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="170.191.0" />
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
    <PackageReference Include="PuppeteerSharp" Version="24.40.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.17" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="PulseAI\Functions\" />
  </ItemGroup>

</Project>
