// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pulse.Models.PulseContext;

#nullable disable

namespace Pulse.ApiService.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    partial class PulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Models.Compounds.Compound", b =>
                {
                    b.Property<string>("CompoundCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("CalculatedCostPerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedSpecificGravity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CarbonBlackCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Colour")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompoundDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CompoundDifficultyMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CompoundRangeId")
                        .HasColumnType("int");

                    b.Property<string>("CompoundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("CostingCostPerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustomSaleFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateCostUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HardnessMeasurement")
                        .HasColumnType("int");

                    b.Property<int?>("HardnessTolerance")
                        .HasColumnType("int");

                    b.Property<string>("HardnessType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsImported")
                        .HasColumnType("bit");

                    b.Property<bool>("OverRideCostPerKg")
                        .HasColumnType("bit");

                    b.Property<bool>("OverRideSpecificGravity")
                        .HasColumnType("bit");

                    b.Property<string>("PolymerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RevisedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RevisionCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("RevisionDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RevisionReason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("RoyaltyCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpecificGravity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CompoundCode");

                    b.HasIndex("CompoundRangeId");

                    b.ToTable("CompoundMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Compounds.CompoundRange", b =>
                {
                    b.Property<int>("CompoundRangeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RangeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompoundRangeId");

                    b.ToTable("CompoundRangeMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Compounds.CompoundRangeProperty", b =>
                {
                    b.Property<int>("CompoundRangePropertyId")
                        .HasColumnType("int");

                    b.Property<int>("CompoundRangeId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CompoundRangePropertyId");

                    b.HasIndex("CompoundRangeId");

                    b.ToTable("CompoundRangePropertyMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Compounds.HardnessType", b =>
                {
                    b.Property<string>("HardnessTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("HardnessTypeName");

                    b.ToTable("HardnessTypeMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Compounds.Polymer", b =>
                {
                    b.Property<string>("PolymerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PolymerName");

                    b.ToTable("PolymerMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientCalendarEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ClientRollerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ClientSpecificationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullClientID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.HasKey("EventId");

                    b.HasIndex("FullClientID");

                    b.ToTable("ClientCalendarEvents", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientContact", b =>
                {
                    b.Property<int>("ClientContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientContactId"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactFax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactMobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DivisionId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("DivisionLineId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullClientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientContactId");

                    b.HasIndex("FullClientID");

                    b.ToTable("ClientContactMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientRoller", b =>
                {
                    b.Property<int>("ClientRollerID")
                        .HasColumnType("int");

                    b.Property<string>("ClientRollerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClientRollerSpecificationID")
                        .HasColumnType("int");

                    b.Property<decimal>("CoverDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShellDefects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShellDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShellLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShellWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClientRollerID");

                    b.HasIndex("ClientRollerSpecificationID");

                    b.ToTable("ClientRollerMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientRollerSpecification", b =>
                {
                    b.Property<int>("ClientRollerSpecificationID")
                        .HasColumnType("int");

                    b.Property<decimal>("AdditionalRollDifficultyMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ArticleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompoundCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal?>("CoverDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CoverLeftOffset")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CoverLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CoverMinimumDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DrawingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullClientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("HardnessRequired")
                        .HasColumnType("int");

                    b.Property<int?>("HardnessToleranceAllowed")
                        .HasColumnType("int");

                    b.Property<string>("HardnessTypeRequired")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProcessID")
                        .HasColumnType("int");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RollerFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RollerType")
                        .HasColumnType("int");

                    b.Property<decimal?>("ShellDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShellLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShellMinimumDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShellTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ShellTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ShellWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClientRollerSpecificationID");

                    b.HasIndex("CompoundCode");

                    b.HasIndex("FullClientID");

                    b.ToTable("ClientRollerSpecificationMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("FullClientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID")
                        .HasDatabaseName("IX_ClientSales_CompanyID");

                    b.HasIndex("FullClientID")
                        .HasDatabaseName("IX_ClientSales_FullClientID");

                    b.HasIndex("PeriodID")
                        .HasDatabaseName("IX_ClientSales_PeriodID");

                    b.ToTable("ClientSales", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.Customer", b =>
                {
                    b.Property<string>("FullClientID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Address1")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address2")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address3")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address4")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address5")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("Ageing01")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Ageing02")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Ageing03")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Ageing04")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Ageing05")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("Blocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CreditLimit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("EMail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullChargeClientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("IndustryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PostalAddress1")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress2")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress3")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress4")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress5")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<bool>("RequireOrderNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SalesRepID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SisterCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TaxCodeID")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("00");

                    b.Property<int?>("TermDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("VATNo")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("FullClientID");

                    b.HasIndex("ClientName")
                        .HasDatabaseName("IX_ClientMaster_ClientName");

                    b.HasIndex("CompanyID");

                    b.HasIndex("IndustryID")
                        .HasDatabaseName("IX_ClientMaster_IndustryID");

                    b.HasIndex("RegionID")
                        .HasDatabaseName("IX_ClientMaster_RegionID");

                    b.HasIndex("SalesRepID")
                        .HasDatabaseName("IX_ClientMaster_SalesRepID");

                    b.ToTable("ClientMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Continent", b =>
                {
                    b.Property<int>("ContinentID")
                        .HasColumnType("int");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ContinentID");

                    b.ToTable("ContinentMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<int>("ContinentID")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryID");

                    b.HasIndex("ContinentID");

                    b.ToTable("CountryMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Province", b =>
                {
                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvinceID");

                    b.HasIndex("CountryID");

                    b.ToTable("ProvinceMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegionID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("RegionMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Industries.Industry", b =>
                {
                    b.Property<int>("IndustryID")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("IndustryID");

                    b.ToTable("IndustryMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryProcess", b =>
                {
                    b.Property<int>("IndustryProcessID")
                        .HasColumnType("int");

                    b.Property<int>("IndustryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IndustryProcessID");

                    b.HasIndex("IndustryID");

                    b.ToTable("IndustryProcessMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryRecommendedCover", b =>
                {
                    b.Property<int>("IndustryRecommendedCoverId")
                        .HasColumnType("int");

                    b.Property<string>("CompoundCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("IndustryRollerEnvironmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("IndustryRecommendedCoverId");

                    b.HasIndex("CompoundCode");

                    b.HasIndex("IndustryRollerEnvironmentId");

                    b.ToTable("IndustryRecommendedCoverMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryRollerEnvironment", b =>
                {
                    b.Property<int>("IndustryRollerEnvironmentId")
                        .HasColumnType("int");

                    b.Property<string>("EnvironmentConditions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<int?>("IndustryProcessId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RollerTypeId")
                        .HasColumnType("int");

                    b.HasKey("IndustryRollerEnvironmentId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("IndustryProcessId");

                    b.HasIndex("RollerTypeId");

                    b.ToTable("IndustryRollerEnvironmentMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Misc.AiQuery", b =>
                {
                    b.Property<int>("AiQueryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiQueryID"));

                    b.Property<int>("DownVote")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpVote")
                        .HasColumnType("int");

                    b.HasKey("AiQueryID");

                    b.ToTable("AiSavedQueries", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Misc.Colour", b =>
                {
                    b.Property<string>("ColourName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ColourName");

                    b.ToTable("ColourMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Misc.EquipmentCategory", b =>
                {
                    b.Property<string>("EquipmentCategoryID")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("EquipmentCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("EquipmentCategoryID");

                    b.ToTable("EquipmentCategoryMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Misc.Period", b =>
                {
                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<string>("CalendarYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PeriodID");

                    b.ToTable("PeriodMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("BranchID");

                    b.ToTable("BranchMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CompanyID");

                    b.ToTable("CompanyMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Division", b =>
                {
                    b.Property<string>("DivisionID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DivisionID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CompanyID");

                    b.ToTable("DivisionMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.SalesRepresentative", b =>
                {
                    b.Property<string>("RepresentativeID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedUserID")
                        .HasColumnType("int");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RepresentativeID");

                    b.HasIndex("CompanyID");

                    b.ToTable("RepresentativeMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.EquipmentCapability", b =>
                {
                    b.Property<string>("EquipmentItemID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductionStageID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("EquipmentItemID", "ProductionStageID");

                    b.HasIndex("ProductionStageID");

                    b.ToTable("EquipmentCapabilities", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.EquipmentItem", b =>
                {
                    b.Property<string>("EquipmentItemID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DivisionID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EquipmentCategoryID")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("EquipmentDifficultyMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1m);

                    b.Property<string>("EquipmentItemDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FixedAssetNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EquipmentItemID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("EquipmentCategoryID");

                    b.ToTable("EquipmentItems", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.ProductionPlanItem", b =>
                {
                    b.Property<int>("ProductionPlanItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionPlanItemID"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("DivisionID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EquipmentItemID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsPulsePlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PlannedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductionStageID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("Unplanned");

                    b.Property<int>("WorkOrderNo")
                        .HasColumnType("int");

                    b.HasKey("ProductionPlanItemID");

                    b.ToTable("ProductionPlanItems", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.ProductionStage", b =>
                {
                    b.Property<int>("ProductionStageId")
                        .HasColumnType("int");

                    b.Property<int>("BaseMinutesAtStage")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DifficultyMeasurement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DivisionID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("HasMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOptional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ProductionStageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresPlanning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiresSignOff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ResultsPage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<int>("WorkTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkTypeID1")
                        .HasColumnType("int");

                    b.HasKey("ProductionStageId");

                    b.HasIndex("DivisionID");

                    b.HasIndex("WorkTypeID");

                    b.HasIndex("WorkTypeID1");

                    b.ToTable("ProductionStageMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.WorkCentre", b =>
                {
                    b.Property<int>("WorkCentreId")
                        .HasColumnType("int");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("DivisionID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("WorkCentreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkCentreId");

                    b.HasIndex("BranchID");

                    b.HasIndex("DivisionID");

                    b.ToTable("WorkCentreMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.WorkCentreFunctions", b =>
                {
                    b.Property<int>("WorkCentreID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductionStageID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("WorkCentreId")
                        .HasColumnType("int");

                    b.HasKey("WorkCentreID", "ProductionStageID");

                    b.HasIndex("ProductionStageID");

                    b.ToTable("WorkCentreFunctionsMapping", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.WorkType", b =>
                {
                    b.Property<int>("WorkTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LockToProductCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TargetWorkingDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("WorkTypeMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WorkTypeID");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_WorkType_IsActive");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_WorkType_SortOrder");

                    b.ToTable("WorkTypeMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Production.WorksOrder", b =>
                {
                    b.Property<int>("WorksOrderNo")
                        .HasColumnType("int");

                    b.Property<string>("ClientOrderNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientPRNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientRFQNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientRollNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ClientRollerID")
                        .HasColumnType("int");

                    b.Property<int?>("ClientRollerSpecificationID")
                        .HasColumnType("int");

                    b.Property<string>("CompoundCode")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CoverCompoundCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal?>("CoverDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DivisionID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FullClientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("InvoicedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaterialCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<int>("ProductionStageID")
                        .HasColumnType("int");

                    b.Property<string>("ProductionStageName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProgressChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgressComment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("ShellDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShellLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UndelQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("WorkTypeID")
                        .HasColumnType("int");

                    b.HasKey("WorksOrderNo")
                        .HasName("PK__WorksOrder");

                    b.HasIndex("ClientRollerID");

                    b.HasIndex("ClientRollerSpecificationID");

                    b.HasIndex("CompoundCode");

                    b.HasIndex("DateStarted")
                        .HasDatabaseName("IX_WorksOrder_DateStarted");

                    b.HasIndex("DivisionID");

                    b.HasIndex("FullClientID")
                        .HasDatabaseName("IX_WorksOrder_FullClientID");

                    b.HasIndex("PeriodID")
                        .HasDatabaseName("IX_WorksOrder_PeriodID");

                    b.HasIndex("ProductionStageID");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WorksOrder_Status");

                    b.HasIndex("WorkTypeID");

                    b.HasIndex("FullClientID", "PeriodID", "Status")
                        .HasDatabaseName("IX_WorksOrder_ClientPeriodStatus");

                    b.ToTable("WorksOrder", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Rollers.RollerType", b =>
                {
                    b.Property<int>("RollerTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RollerTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RollerTypeID");

                    b.ToTable("RollerTypeMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Rollers.ShellType", b =>
                {
                    b.Property<int>("ShellTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShellTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ShellTypeID");

                    b.ToTable("ShellTypeMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Users.User", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("UserMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Users.UserFavouriteQry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QueryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavouriteQuery", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Compounds.Compound", b =>
                {
                    b.HasOne("Pulse.Models.Compounds.CompoundRange", "CompoundRange")
                        .WithMany("Compounds")
                        .HasForeignKey("CompoundRangeId");

                    b.Navigation("CompoundRange");
                });

            modelBuilder.Entity("Pulse.Models.Compounds.CompoundRangeProperty", b =>
                {
                    b.HasOne("Pulse.Models.Compounds.CompoundRange", "CompoundRange")
                        .WithMany("CompoundRangeProperties")
                        .HasForeignKey("CompoundRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompoundRange");
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientCalendarEvent", b =>
                {
                    b.HasOne("Pulse.Models.Customers.Customer", "Customer")
                        .WithMany("ClientCalendarEvents")
                        .HasForeignKey("FullClientID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientContact", b =>
                {
                    b.HasOne("Pulse.Models.Customers.Customer", "Customer")
                        .WithMany("ClientContacts")
                        .HasForeignKey("FullClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientRoller", b =>
                {
                    b.HasOne("Pulse.Models.Customers.ClientRollerSpecification", "ClientRollerSpecification")
                        .WithMany("ClientRollers")
                        .HasForeignKey("ClientRollerSpecificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientRollerSpecification");
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientRollerSpecification", b =>
                {
                    b.HasOne("Pulse.Models.Compounds.Compound", "Compound")
                        .WithMany("ClientRollerSpecifications")
                        .HasForeignKey("CompoundCode");

                    b.HasOne("Pulse.Models.Customers.Customer", "Customer")
                        .WithMany("ClientRollerSpecifications")
                        .HasForeignKey("FullClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compound");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientSales", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Customers.Customer", "Customer")
                        .WithMany("ClientSales")
                        .HasForeignKey("FullClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Misc.Period", "Period")
                        .WithMany("ClientSales")
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Pulse.Models.Customers.Customer", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Industries.Industry", "Industry")
                        .WithMany("Customers")
                        .HasForeignKey("IndustryID");

                    b.HasOne("Pulse.Models.Geographic.Region", "Region")
                        .WithMany("Customers")
                        .HasForeignKey("RegionID");

                    b.HasOne("Pulse.Models.Organizational.SalesRepresentative", "SalesRepresentative")
                        .WithMany("Customers")
                        .HasForeignKey("SalesRepID");

                    b.Navigation("Company");

                    b.Navigation("Industry");

                    b.Navigation("Region");

                    b.Navigation("SalesRepresentative");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Country", b =>
                {
                    b.HasOne("Pulse.Models.Geographic.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Province", b =>
                {
                    b.HasOne("Pulse.Models.Geographic.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Region", b =>
                {
                    b.HasOne("Pulse.Models.Geographic.Province", "Province")
                        .WithMany("Regions")
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryProcess", b =>
                {
                    b.HasOne("Pulse.Models.Industries.Industry", "Industry")
                        .WithMany("IndustryProcesses")
                        .HasForeignKey("IndustryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryRecommendedCover", b =>
                {
                    b.HasOne("Pulse.Models.Compounds.Compound", "Compound")
                        .WithMany("IndustryRecommendedCovers")
                        .HasForeignKey("CompoundCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Industries.IndustryRollerEnvironment", "IndustryRollerEnvironment")
                        .WithMany("IndustryRecommendedCovers")
                        .HasForeignKey("IndustryRollerEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compound");

                    b.Navigation("IndustryRollerEnvironment");
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryRollerEnvironment", b =>
                {
                    b.HasOne("Pulse.Models.Industries.Industry", "Industry")
                        .WithMany("IndustryRollerEnvironments")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Industries.IndustryProcess", "IndustryProcess")
                        .WithMany("IndustryRollerEnvironments")
                        .HasForeignKey("IndustryProcessId");

                    b.HasOne("Pulse.Models.Rollers.RollerType", "RollerType")
                        .WithMany("IndustryRollerEnvironments")
                        .HasForeignKey("RollerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("IndustryProcess");

                    b.Navigation("RollerType");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Division", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Branch", "Branch")
                        .WithMany("Divisions")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Organizational.Company", "Company")
                        .WithMany("Divisions")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.SalesRepresentative", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Company", "Company")
                        .WithMany("SalesRepresentatives")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Pulse.Models.Production.EquipmentCapability", b =>
                {
                    b.HasOne("Pulse.Models.Production.EquipmentItem", "EquipmentItem")
                        .WithMany("EquipmentCapabilities")
                        .HasForeignKey("EquipmentItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Production.ProductionStage", "ProductionStage")
                        .WithMany("EquipmentCapabilities")
                        .HasForeignKey("ProductionStageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentItem");

                    b.Navigation("ProductionStage");
                });

            modelBuilder.Entity("Pulse.Models.Production.EquipmentItem", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Misc.EquipmentCategory", "EquipmentCategory")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("EquipmentCategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Division");

                    b.Navigation("EquipmentCategory");
                });

            modelBuilder.Entity("Pulse.Models.Production.ProductionStage", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Production.WorkType", "WorkType")
                        .WithMany()
                        .HasForeignKey("WorkTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Production.WorkType", null)
                        .WithMany("ProductionStages")
                        .HasForeignKey("WorkTypeID1");

                    b.Navigation("Division");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("Pulse.Models.Production.WorkCentre", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Organizational.Division", null)
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Models.Production.WorkCentreFunctions", b =>
                {
                    b.HasOne("Pulse.Models.Production.ProductionStage", "ProductionStage")
                        .WithMany()
                        .HasForeignKey("ProductionStageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Production.WorkCentre", "WorkCentre")
                        .WithMany("WorkCentreFunctions")
                        .HasForeignKey("WorkCentreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionStage");

                    b.Navigation("WorkCentre");
                });

            modelBuilder.Entity("Pulse.Models.Production.WorksOrder", b =>
                {
                    b.HasOne("Pulse.Models.Customers.ClientRoller", "ClientRoller")
                        .WithMany("WorksOrders")
                        .HasForeignKey("ClientRollerID");

                    b.HasOne("Pulse.Models.Customers.ClientRollerSpecification", "ClientRollerSpecification")
                        .WithMany("WorksOrders")
                        .HasForeignKey("ClientRollerSpecificationID");

                    b.HasOne("Pulse.Models.Compounds.Compound", "Compound")
                        .WithMany("WorksOrders")
                        .HasForeignKey("CompoundCode");

                    b.HasOne("Pulse.Models.Organizational.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Customers.Customer", "Customer")
                        .WithMany("WorksOrders")
                        .HasForeignKey("FullClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Misc.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Production.ProductionStage", "ProductionStage")
                        .WithMany()
                        .HasForeignKey("ProductionStageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Production.WorkType", "WorkType")
                        .WithMany()
                        .HasForeignKey("WorkTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientRoller");

                    b.Navigation("ClientRollerSpecification");

                    b.Navigation("Compound");

                    b.Navigation("Customer");

                    b.Navigation("Division");

                    b.Navigation("Period");

                    b.Navigation("ProductionStage");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("Pulse.Models.Users.UserFavouriteQry", b =>
                {
                    b.HasOne("Pulse.Models.Misc.AiQuery", "AiQuery")
                        .WithMany("UserFavouriteQueries")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Users.User", "User")
                        .WithMany("UserFavouriteQueries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiQuery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pulse.Models.Compounds.Compound", b =>
                {
                    b.Navigation("ClientRollerSpecifications");

                    b.Navigation("IndustryRecommendedCovers");

                    b.Navigation("WorksOrders");
                });

            modelBuilder.Entity("Pulse.Models.Compounds.CompoundRange", b =>
                {
                    b.Navigation("CompoundRangeProperties");

                    b.Navigation("Compounds");
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientRoller", b =>
                {
                    b.Navigation("WorksOrders");
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientRollerSpecification", b =>
                {
                    b.Navigation("ClientRollers");

                    b.Navigation("WorksOrders");
                });

            modelBuilder.Entity("Pulse.Models.Customers.Customer", b =>
                {
                    b.Navigation("ClientCalendarEvents");

                    b.Navigation("ClientContacts");

                    b.Navigation("ClientRollerSpecifications");

                    b.Navigation("ClientSales");

                    b.Navigation("WorksOrders");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Continent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Province", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Region", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Pulse.Models.Industries.Industry", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("IndustryProcesses");

                    b.Navigation("IndustryRollerEnvironments");
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryProcess", b =>
                {
                    b.Navigation("IndustryRollerEnvironments");
                });

            modelBuilder.Entity("Pulse.Models.Industries.IndustryRollerEnvironment", b =>
                {
                    b.Navigation("IndustryRecommendedCovers");
                });

            modelBuilder.Entity("Pulse.Models.Misc.AiQuery", b =>
                {
                    b.Navigation("UserFavouriteQueries");
                });

            modelBuilder.Entity("Pulse.Models.Misc.EquipmentCategory", b =>
                {
                    b.Navigation("EquipmentItems");
                });

            modelBuilder.Entity("Pulse.Models.Misc.Period", b =>
                {
                    b.Navigation("ClientSales");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Branch", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Divisions");

                    b.Navigation("SalesRepresentatives");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.SalesRepresentative", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Pulse.Models.Production.EquipmentItem", b =>
                {
                    b.Navigation("EquipmentCapabilities");
                });

            modelBuilder.Entity("Pulse.Models.Production.ProductionStage", b =>
                {
                    b.Navigation("EquipmentCapabilities");
                });

            modelBuilder.Entity("Pulse.Models.Production.WorkCentre", b =>
                {
                    b.Navigation("WorkCentreFunctions");
                });

            modelBuilder.Entity("Pulse.Models.Production.WorkType", b =>
                {
                    b.Navigation("ProductionStages");
                });

            modelBuilder.Entity("Pulse.Models.Rollers.RollerType", b =>
                {
                    b.Navigation("IndustryRollerEnvironments");
                });

            modelBuilder.Entity("Pulse.Models.Users.User", b =>
                {
                    b.Navigation("UserFavouriteQueries");
                });
#pragma warning restore 612, 618
        }
    }
}
