// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pulse.Models.PulseContext;

#nullable disable

namespace Pulse.ApiService.Migrations
{
    [DbContext(typeof(PulseDbContext))]
    partial class PulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Models.Customers.ClientSales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("FullClientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FullClientID");

                    b.HasIndex("PeriodID");

                    b.ToTable("ClientSales", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.Customer", b =>
                {
                    b.Property<string>("FullClientID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Address1")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address2")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address3")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address4")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Address5")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("Ageing01")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ageing02")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ageing03")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ageing04")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ageing05")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EMail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullChargeClientID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("IndustryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PostalAddress1")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress2")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress3")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress4")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalAddress5")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<bool>("RequireOrderNo")
                        .HasColumnType("bit");

                    b.Property<string>("SalesRepID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SisterCompany")
                        .HasColumnType("bit");

                    b.Property<string>("TaxCodeID")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("TermDays")
                        .HasColumnType("int");

                    b.Property<string>("VATNo")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("FullClientID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("IndustryID");

                    b.HasIndex("RegionID");

                    b.HasIndex("SalesRepID");

                    b.ToTable("ClientMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Continent", b =>
                {
                    b.Property<int>("ContinentID")
                        .HasColumnType("int");

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ContinentID");

                    b.ToTable("ContinentMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<int>("ContinentID")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryID");

                    b.HasIndex("ContinentID");

                    b.ToTable("CountryMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Province", b =>
                {
                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProvinceID");

                    b.HasIndex("CountryID");

                    b.ToTable("ProvinceMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RegionID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("RegionMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Misc.AiQuery", b =>
                {
                    b.Property<int>("AiQueryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiQueryID"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AiQueryID");

                    b.ToTable("AiSavedQueries", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Misc.Industry", b =>
                {
                    b.Property<int>("IndustryID")
                        .HasColumnType("int");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("IndustryID");

                    b.ToTable("IndustryMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Misc.Period", b =>
                {
                    b.Property<int>("PeriodID")
                        .HasColumnType("int");

                    b.Property<string>("CalendarYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PeriodID");

                    b.ToTable("PeriodMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BranchID");

                    b.ToTable("BranchMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CompanyID");

                    b.ToTable("CompanyMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Division", b =>
                {
                    b.Property<string>("DivisionID")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DivisionID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CompanyID");

                    b.ToTable("DivisionMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.SalesRepresentative", b =>
                {
                    b.Property<string>("RepresentativeID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedUserID")
                        .HasColumnType("int");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RepresentativeID");

                    b.HasIndex("CompanyID");

                    b.ToTable("RepresentativeMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Organizational.User", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("UserMaster", (string)null);
                });

            modelBuilder.Entity("Pulse.Models.Customers.ClientSales", b =>
                {
                    b.HasOne("Pulse.Models.Customers.Customer", "Customer")
                        .WithMany("ClientSales")
                        .HasForeignKey("FullClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Misc.Period", "Period")
                        .WithMany("ClientSales")
                        .HasForeignKey("PeriodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Pulse.Models.Customers.Customer", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Misc.Industry", "Industry")
                        .WithMany("Customers")
                        .HasForeignKey("IndustryID");

                    b.HasOne("Pulse.Models.Geographic.Region", "Region")
                        .WithMany("Customers")
                        .HasForeignKey("RegionID");

                    b.HasOne("Pulse.Models.Organizational.SalesRepresentative", "SalesRepresentative")
                        .WithMany("Customers")
                        .HasForeignKey("SalesRepID");

                    b.Navigation("Company");

                    b.Navigation("Industry");

                    b.Navigation("Region");

                    b.Navigation("SalesRepresentative");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Country", b =>
                {
                    b.HasOne("Pulse.Models.Geographic.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Province", b =>
                {
                    b.HasOne("Pulse.Models.Geographic.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Region", b =>
                {
                    b.HasOne("Pulse.Models.Geographic.Province", "Province")
                        .WithMany("Regions")
                        .HasForeignKey("ProvinceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Division", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Branch", "Branch")
                        .WithMany("Divisions")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pulse.Models.Organizational.Company", "Company")
                        .WithMany("Divisions")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.SalesRepresentative", b =>
                {
                    b.HasOne("Pulse.Models.Organizational.Company", "Company")
                        .WithMany("SalesRepresentatives")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Pulse.Models.Customers.Customer", b =>
                {
                    b.Navigation("ClientSales");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Continent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Province", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Pulse.Models.Geographic.Region", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Pulse.Models.Misc.Industry", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Pulse.Models.Misc.Period", b =>
                {
                    b.Navigation("ClientSales");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Branch", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Divisions");

                    b.Navigation("SalesRepresentatives");
                });

            modelBuilder.Entity("Pulse.Models.Organizational.SalesRepresentative", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
