<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\js\DashboardFH.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  

  <ItemGroup>
    <ProjectReference Include="..\Pulse.Models\Pulse.Models.csproj" />
    <ProjectReference Include="..\Pulse.ServiceDefaults\Pulse.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.1.0" />
    <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="13.1.0" />
    <PackageReference Include="Blazor.SessionStorage" Version="9.0.1" />
    <PackageReference Include="BlazorAnimation" Version="2.2.0" />
    <PackageReference Include="BootstrapBlazor" Version="10.2.0" />
    <PackageReference Include="BootstrapBlazor.Chart" Version="10.0.2" />
    <PackageReference Include="BootstrapBlazor.FontAwesome" Version="10.0.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Markdig" Version="0.44.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.2" />
    
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" Version="10.1.0" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter" Version="4.13.2" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.13.2" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <PackageReference Include="Toolbelt.Blazor.SpeechRecognition" Version="1.0.0" />
    <PackageReference Include="Toolbelt.Blazor.SpeechSynthesis" Version="11.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\js\scriptLoader.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\SiteSensorManagement.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Components\Layout\MasterAIMenu.razor.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Components\Layout\MasterLayout.razor.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\AdminZone\SiteSensorManagement.razor.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\AiZone\FlapperPg - BU2.razor.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\AiZone\FlapperPg.razor.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\AiZone\TablesPg.razor.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\AiZone\FlapperOldPg.razor.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\EmployeeZone\Customers\ClientSales.razor.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\EmployeeZone\Production\DashboardFH.razor.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Components\Pages\EmployeeZone\Production\WorkInProgress.razor.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Components\PulseComponents\Cards\PulseAICard.razor.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
